notifications:
  email: false
  slack:
    secure: mPKaUM9AambwostCzge+bfpC4l2YStah+/pr1BfZbTDRwb3CVsbn69mIRpIu+M3o2aH+Kr2WuBG6SvmMU+nvYjdBsz7iJDJQy98+9rTTNs3s5ski3ZrltjPC6pYiituHnuFfSe5ENt/JpiLKQ8vzL4puRPLeKZ0RS/0KtInlaN7Twg6jc5bhS+mzLQScpM5uYfXdv7d9snHScjoGYbmv07h+jtH1vxRVm++nw9iYVTmZeYbC5rskYW1RwlMmrLaq567v//2jaOF9Op8wAfujxDSR/zze7RLlDBwdr2mFwsKDTpcANur3XJge57fZi622Xe/rRwLAzVxCeG35zJkef+7XqVaJGMgawLDUyTRu8dR9Ck47ah3RR2s6Q4dNThrCndlmdkcPnAbgU74jiHyfUONl51vTDPXr2Na2+x1afm5cM+/UbjACMat7zJal+BhO7IJKbW1AWJZ6BfERKtiQ8Zhdg05myvBw9YFCUv0nvyDt8WIxGYjJMpEaHmX/8BmKbFcp+J0ftDD3iSlB9DmC4J2SqPDKj+YX4B+ccCfHynkhIqQlBx6bKgh1rm3VY7Yf0mvLuQM8yRU7NDxJgpYG9zMc3XUKQPlgHLgrccbeFn9VZUs4In+H5Gj9sfqYPXfI6fP4ADZjOuNp1wUnd0ivg1SXnskp57Cllt+apHsmN84=

language: scala

services:
  - docker

scala:
  - 2.12.4

jdk:
  - oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_install:
  - cd docker/
  - cp .env.dist .env
  - docker-compose up -d
  - cd ..
  - sbt createDbTables

script:
  - sbt clean
  - sbt prep # Check pre-push style hook in order to avoid `push --no-verify` h4ck3rs
  # Execute the tests including code coverage. More info: https://github.com/scoverage/sbt-coveralls
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M coverage test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - sbt coverageReport coveralls
